import { Metadata } from "next"


export const metadata: Metadata = {
  title: {
    absolute:"",
    default:"Default Nextjs",
    template:"%s | Next.js template ",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      {/* <link rel="icon" href="https://gensh.honeyhunterworld.com/img/shougun_052_icon_70.webp?x46552" sizes="any" /> */}
      <body>
        <header style={{background:"lightblue", padding:"1rem"}}>
            This is header
        </header>
        {children}
        <footer style={{background:"ghostwhite", padding:"1rem"}}>
          This is footer
        </footer>
      </body>
    </html>
  )
}
